import { chromium } from 'playwright';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import ts from 'typescript';
const css=await readFile('themes/kujo.css','utf8');
const cleanup=await readFile('src/cleanup.ts','utf8');
const effects=(await readFile('src/effects.ts','utf8')).replace(/^import .*$/m,'');
const js=ts.transpile((cleanup+'\n'+effects).replace(/export /g,''),{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}).replace(/export /g,'');
const browser=await chromium.launch({channel:process.env.KUJO_BROWSER||'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.setContent('<html class="dark"><head></head><body><button>Run</button><input aria-label="Command"><div class="bb-code-highlight">Code</div><div data-timeline-row-id="settled"><span class="opacity-40">Worked for 85ms</span></div></body></html>');
const cdp=await page.context().newCDPSession(page);await cdp.send('Performance.enable');
const metrics=async()=>Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value]));
const before=await metrics();await page.waitForTimeout(13000);const base=await metrics();
await page.addScriptTag({content:js+'\nwindow.kujoTestMount = mountSignal;'});
await page.evaluate(css=>{const s=document.createElement('style');s.id='theme-under-test';s.textContent=css;document.head.append(s);},css);
await page.evaluate(()=>{window.controller=new AbortController();window.dispose=window.kujoTestMount({signal:window.controller.signal});});
const start=await metrics();await page.waitForTimeout(13000);const end=await metrics();
const check=await page.evaluate(()=>({canvas:getComputedStyle(document.documentElement).getPropertyValue('--canvas').trim(),decoration:getComputedStyle(document.querySelector('.bb-kujo-signal')).pointerEvents,overflow:document.documentElement.scrollWidth>innerWidth}));
assert.equal(await page.locator('[data-timeline-row-id] .opacity-40').evaluate(e=>getComputedStyle(e).opacity),'1');
assert.equal(check.decoration,'none');assert.equal(check.overflow,false);
await page.getByRole('button',{name:'Run'}).focus();
assert.equal(await page.getByRole('button').evaluate(e=>getComputedStyle(e).outlineStyle),'solid');
await page.getByRole('textbox').fill('kujo check');assert.equal(await page.getByRole('textbox').inputValue(),'kujo check');
await page.emulateMedia({reducedMotion:'reduce'});
assert.equal(await page.locator('.bb-kujo-signal > span').evaluate(e=>getComputedStyle(e).animationName),'none');
await page.emulateMedia({reducedMotion:'no-preference'});
for(const width of [375,768,1024,1440,2560]) {await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
await page.evaluate(()=>document.documentElement.className='light');
assert.equal(await page.locator('.bb-kujo-signal').evaluate(e=>getComputedStyle(e).display),'none');
await page.evaluate(()=>{document.documentElement.className='dark';document.querySelector('#theme-under-test').remove();});
assert.equal(await page.locator('.bb-kujo-signal').evaluate(e=>getComputedStyle(e).display),'none');
await page.evaluate(()=>{window.controller.abort();window.dispose();});
assert.equal(await page.locator('.bb-kujo-signal').count(),0);
const nodesBefore=await cdp.send('Memory.getDOMCounters');
await page.evaluate(()=>{for(let i=0;i<100;i++){const c=new AbortController();const d=window.kujoTestMount({signal:c.signal});c.abort();d();}const c=new AbortController();c.abort();window.kujoTestMount({signal:c.signal});});
await cdp.send('HeapProfiler.collectGarbage');
const nodesAfter=await cdp.send('Memory.getDOMCounters');
assert.equal(await page.locator('.bb-kujo-signal').count(),0);
assert.ok(nodesAfter.jsEventListeners<=nodesBefore.jsEventListeners);
assert.deepEqual(errors,[]);
const report={kind:'Isolated Chromium CSS/content-script checks; not whole-app performance',date:new Date().toISOString(),browser:browser.version(),viewports:[375,768,1024,1440,2560],cycles:100,errors,checks:check,listenersBefore:nodesBefore.jsEventListeners,listenersAfter:nodesAfter.jsEventListeners,baselineTaskSeconds:base.TaskDuration-before.TaskDuration,themedTaskSeconds:end.TaskDuration-start.TaskDuration,baselineHeap:base.JSHeapUsedSize,themedHeap:end.JSHeapUsedSize,baselineLayoutCount:base.LayoutCount-before.LayoutCount,themedLayoutCount:end.LayoutCount-start.LayoutCount};
await mkdir('artifacts',{recursive:true});await writeFile('artifacts/browser-qa.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));await browser.close();
